### ISSUE TITLE
Floating palette selects widgets

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/dashboard#39]
I've noticed that if you drag the palette around the dashboard, it selects (highlights) widgets, menus etc in the dashboard and palette - see screenshot.

![select](https://cloud.githubusercontent.com/assets/973580/19474608/369df9be-9528-11e6-8f63-a75741c3449e.png)

Paul

**Comment by firefox7518** [comment]
I tried to fix it with my new PR. I added a pauseEvent to it. It seems to solve it as I'm not able anymore to replicate this.

**Comment by firefox7518** [comment]
fixed with update from Matts Jquery code

**Comment by Paul-Reed** [comment]
Still persists here with Matt's jQuery code applied;

![select1](https://cloud.githubusercontent.com/assets/973580/19577954/5ecff032-9711-11e6-9802-945427278ab5.gif)

Paul

**Comment by firefox7518** [comment]
Does not happen for me on any browser. Which one are you using?

**Comment by Paul-Reed** [comment]
fixed by https://github.com/emoncms/dashboard/pull/48
